pytest==3.0.6
django>=1.9.1
retrying
pika
pika_pool

